#veja sรณ, aprendendo a usar spring
spring:
    datasource:
        url: jdbc:h2:mem:banco_dados_credito
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        show-sql?: true
        hibernate:
            proprerties:
                hibernate.format_sql: true